services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      TZ: UTC
      PGTZ: UTC
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
    networks:
      - adminer-network

  adminer:
    image: adminer
    ports:
      - "8080:8080" # Expose Adminer on port 8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres # Connect Adminer to the 'postgres' service
    networks:
      - adminer-network


volumes:
  postgres-data:

networks:
  adminer-network: